Iqra Muqaddas

---

Week 1

---
Data Cleaning

# Importing Necessary Libraries

In [1]:
import pandas as pd
import numpy as np

# Loading the Dataset

In [2]:
df = pd.read_csv("/content/messy_applicants.csv")
df.head()

,Applicant_ID,Applicant_Name,Email,Phone,Domain_Applied,University,Application_Date,Status
0,APP0001,Allison Hill,donaldgarcia@example.net,+1-219-560-0133,WEB DEV,NaN,2026-01-02,Rejected
1,APP0002,Sean Blake,helenpeterson@example.org,651.216.1559,Web Development,Uet lahore,28-Apr-2026,selected
2,APP0003,Edward Fuller,barbara10@example.net,441.731.6475,Artificial Intelligence,NaN,16-Jun-2026,NaN
3,APP0004,Maria Lynch,amandasanchez@example.com,(748)535-0305x6413,Web Development,NaN,2026-03-07,Rejected
4,APP0005,Derek Wright,julie69@example.com,(332)887-1012x269,Deep Learning,U.E.T,2026-04-25,Rejected

 # Understanding Data Before Cleaning

In [4]:

df_shape = df.shape

print("=="*60)
print("shape of df" , df_shape  )
print("=="*60)

print(df.info())

========================================================================================================================
shape of df (1000, 8)
========================================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant_ID      1000 non-null   object
 1   Applicant_Name    950 non-null    object
 2   Email             850 non-null    object
 3   Phone             1000 non-null   object
 4   Domain_Applied    1000 non-null   object
 5   University        650 non-null    object
 6   Application_Date  1000 non-null   object
 7   Status            850 non-null    object
dtypes: object(8)
memory usage: 62.6+ KB
None

**The dataset has 1000 rows and 8 columns where Applicant Name has 50 missing values, Email has 150 missing values, University has 350 missing values, Status has 150 missing values. There are 0 duplicate records, and Application Date is currently stored as text (object type), not as an
actual date."**

In [5]:
missing_values = df.isnull().sum() # exact count of missing values per column
duplicates = df.duplicated().sum()  # how many exact duplicate rows exist
print(" Missing values:\n" , missing_values)

print("="*60)

print("Duplicates:", duplicates)

 Missing values:
 Applicant_ID          0
Applicant_Name       50
Email               150
Phone                 0
Domain_Applied        0
University          350
Application_Date      0
Status              150
dtype: int64
============================================================
Duplicates: 0

In [6]:
count = df[df['Applicant_Name'].isna() & df['Email'].isna()].shape[0]

print("Rows where both columns have missing values:", count)

Rows where both columns have missing values: 50

#Handle Missing Values

**I dropped rows with missing Applicant Name because a nameless application isn't usable for outreach.**

In [7]:
df.dropna(subset=['Applicant_Name', 'Email'], how='all', inplace=True)

In [8]:
df.isnull().sum()

Applicant_ID          0
Applicant_Name        0
Email               100
Phone                 0
Domain_Applied        0
University          300
Application_Date      0
Status              142
dtype: int64

**I filled the missing Email records with "not_provided@example.com" because we have phone numbers and names through which we can outreach the applicants**

In [9]:
df['Email'] = df['Email'].fillna("not_provided@example.com")

# Standardize Text Fields

**Checking leading and trailing whitespaces in Applicant Column**

In [10]:
for name in df['Applicant_Name']:
  if name != name.strip():
    print(repr(name))

' Carmen Smith '
' Lindsey Walker '
' Kelly Campbell '
' Sara Carpenter '
' Brittney Olson '
' Meagan Calderon '
' Shelly Spencer '
' Alfred Galvan '
' Michael Welch '
' Courtney Hall '
' Michael Guerrero '
' Jennifer White '
' Chad Roach '
' Thomas Rios '
' Timothy Cole '
' Christopher Cooper '
' Nicholas Smith '
' Scott Thomas '
' Matthew Miller '
' Kelly Calderon '
' Nicole Carson '
' Jennifer Kennedy '
' Lance Lynn '
' Brad Russo '
' Dominique Schneider '
' Ralph Dawson '
' John Lopez '
' Brooke Walters '
' Sheila Black '
' Theresa Freeman '
' Victor Hill '
' Mrs. Courtney Wong '
' Roger Russo '
' Dylan Strong '
' Kenneth Turner '
' Dan Phillips '
' Robert Gonzalez '
' David Dean '
' Amanda Ellison '
' Jessica Watts '
' Laura Sparks '
' Dr. Tamara Roberts '
' Brandon Johnson '
' Joel Gonzales '
' Haley Jackson '
' Tony Brown '
' Richard Wade '
' Pamela Cohen '
' Heather Gallegos '
' Matthew Barrett '

**Removing leading and trailing whitespaces from Applicant Names**

In [11]:
df['Applicant_Name'] = df['Applicant_Name'].str.strip()

**Checking the inconsistent names in the University column**

In [12]:
df['University'].value_counts()

University
UET                                         452
uet                                          56
University of Engineering and Technology     50
Uet lahore                                   46
U.E.T                                        46
Name: count, dtype: int64

**I filled missing University with "University of Engineering and Technology" instead of dropping because the inconsistent patterns shows data of the same university**

In [13]:
df["University"] = df['University'].fillna("University of Engineering and Technology")

**Checking Inconsistencies in the Status Column**

In [14]:
df['Status'].value_counts()

Status
Selected        204
Rejected        198
Under Review    165
rejected         56
under review     31
Under review     31
SELECTED         30
UNDER REVIEW     29
selected         23
sElEcTeD         22
REJECTED         19
Name: count, dtype: int64

**I filled the missing Status values with Under Review, it likely means the application hasn't been processed yet**

In [15]:
df["Status"] = df['Status'].fillna("Under Review")

In [16]:
df.isnull().sum()

Applicant_ID        0
Applicant_Name      0
Email               0
Phone               0
Domain_Applied      0
University          0
Application_Date    0
Status              0
dtype: int64

**Checking Inconsistencies in the Domain Applied Column**

In [17]:
df['Domain_Applied'].value_counts()

Domain_Applied
Deep Learning              172
Machine Learning           155
Computer Vision            153
Data Science               138
Web Development            129
Artificial Intelligence    105
Web development             15
ARTIFICIAL INTELLIGENCE     14
data science                12
WEB DEV                     11
artificial intelligence     10
DATA SCIENCE                10
web dev                      9
AI                           9
Data science                 8
Name: count, dtype: int64

**Replacing inconsistencies with uniform domain values**

In [18]:
df['Domain_Applied'] = df['Domain_Applied'].replace({
    'web dev': 'Web Development',
    'Web development': 'Web Development',
    'WEB DEV': 'Web Development',
    "data science": "Data Science",
    "DATA SCIENCE": "Data Science",
    "Data science": "Data Science",
    "AI": "Artificial Intelligence",
    "artificial intelligence": "Artificial Intelligence",
    "ARTIFICIAL INTELLIGENCE": "Artificial Intelligence"
})

**Checking that the formatting is consistent now in Domain Applied Column**

In [19]:
df['Domain_Applied'].unique()

array(['Web Development', 'Artificial Intelligence', 'Deep Learning',
       'Computer Vision', 'Data Science', 'Machine Learning'],
      dtype=object)

**Replacing inconsistencies with uniform values in both University and Status column**

In [20]:
df["University"] = df['University'].replace({
    "UET" : "University of Engineering and Technology",
    "U.E.T": "University of Engineering and Technology",
    "uet": "University of Engineering and Technology",
    "Uet lahore": "University of Engineering and Technology"
})

df['Status'] = df["Status"].replace({
    "under review": "Under Review",
    "UNDER REVIEW": "Under Review",
    "Under review": "Under Review",
    "selected": "Selected",
    "SELECTED": "Selected",
    "sElEcTeD": "Selected",
    "rejected": "Rejected",
    "REJECTED": "Rejected",
    "rejected": "Rejected"
})

**Checking that the formatting is consistent now in University Column**

In [21]:
df['University'].unique()

array(['University of Engineering and Technology'], dtype=object)

In [22]:
df['Email'].head(10)

0     donaldgarcia@example.net
1    helenpeterson@example.org
2        barbara10@example.net
3    amandasanchez@example.com
4          julie69@example.com
5          kayla51@example.com
6           john39@example.org
7      wrightcaleb@example.org
8         esanchez@example.com
9           DWHITE@EXAMPLE.ORG
Name: Email, dtype: object

**Removing the whitespsaces from Email Column and Formatting the mixed cases to lower cases**

In [23]:
df['Email'] = df['Email'].str.strip().str.lower()

In [24]:
df['Application_Date'].head()

0     2026-01-02
1    28-Apr-2026
2    16-Jun-2026
3     2026-03-07
4     2026-04-25
Name: Application_Date, dtype: object

**Converting the Application Date column which as mixed date formatting to consistent format and changing its datatype to datetime**

In [25]:
df['Application_Date'] = pd.to_datetime(
    df['Application_Date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)
df['Application_Date']

0     2026-01-02
1     2026-04-28
2     2026-06-16
3     2026-03-07
4     2026-04-25
         ...
995   2026-03-08
996   2026-02-27
997   2026-09-07
998   2025-12-01
999   2026-10-12
Name: Application_Date, Length: 950, dtype: datetime64[ns]

In [26]:
df['Phone']

0            +1-219-560-0133
1               651.216.1559
2               441.731.6475
3         (748)535-0305x6413
4          (332)887-1012x269
               ...
995            (498)262-2699
996      +1-929-998-3358x768
997      +1-831-253-9839x122
998    001-914-730-4913x4103
999     001-524-205-9208x235
Name: Phone, Length: 950, dtype: object

**Removing all the whitespaces and other characters from phone numbers and storing it as string datatype**

In [27]:
df['Phone'] = df['Phone'].astype('string').str.strip()

df['Phone'] = df['Phone'].str.replace(
    r'\D', '', regex=True
)
df['Phone']

0            12195600133
1             6512161559
2             4417316475
3         74853503056413
4          3328871012269
             ...
995           4982622699
996       19299983358768
997       18312539839122
998    00191473049134103
999     0015242059208235
Name: Phone, Length: 950, dtype: string

# Verifying fixes worked

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 950 entries, 0 to 999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant_ID      950 non-null    object
 1   Applicant_Name    950 non-null    object
 2   Email             950 non-null    object
 3   Phone             950 non-null    string
 4   Domain_Applied    950 non-null    object
 5   University        950 non-null    object
 6   Application_Date  950 non-null    datetime64[ns]
 7   Status            950 non-null    object
dtypes: datetime64[ns](1), object(6), string(1)
memory usage: 66.8+ KB

# Saving the cleaned Dataset in the comma separated file(csv)

In [29]:
df.to_csv("cleaned_applicants.csv", index=False)

 # Data Quality Summary

**Issues Found**
1.   Applicant Name has 50, Email has 150, University has 350 , Status has 150 missing values. There are 0 duplicate records, and Application Date is currently stored as text (object type), not as an actual date.
2.   There are 0 duplicate record.
3.   Application Date is currently stored as text (object type), not as an actual date.
4.    Domain Applied had different spelling/casing variations for  
  only 6 real domains.
5. Phone numbers contained inconsistent dash/space formatting.
6. Status had different spelling/casing variations for  
  only 3 real values

**Actions Taken**
1.   Dropped 50 Applicant records as they are unusable without identification
2.   Filled university with the repeating value as the variations represent a single university.
3.  Filled missing Status with "Under Review" (default for unprocessed
applications)
4. Standardized the Status, Domain Applied and University column in consistent categories.
5.  Converted Application Date to proper datetime format.
6. Cleaned Phone number formatting for consistency.

**Final dataset: 950 rows, 8 columns, no missing values in critical  
fields, no duplicates, consistent formatting throughout.**